# Generated by Django 5.1.6 on 2025-02-12 00:45

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atc', '0003_atc_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=model_utils.fields.StatusField(choices=[('0', 'None'), ('1', 'Stopped'), ('2', 'Pushback'), ('3', 'Taxiing'), ('4', 'Departing'), ('5', 'Turning'), ('6', 'Climbing'), ('7', 'Cruising'), ('8', 'Approaching'), ('9', 'Landing'), ('10', 'Touchdown'), ('11', 'Crosswind'), ('12', 'Downwind'), ('13', 'Base'), ('14', 'Straight'), ('15', 'Final'), ('16', 'Short of runway'), ('21', 'On Hold'), ('17', 'Lined up'), ('18', 'Tunned'), ('19', 'Parking'), ('20', 'Lining up'), ('22', 'Rolling'), ('23', 'Cross rwy')], default='0', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
