# Generated by Django 2.1.7 on 2019-03-11 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=8)),
                ('freq', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('altitude', models.IntegerField(default=0)),
                ('model', models.CharField(blank=True, max_length=96, null=True)),
                ('state', models.IntegerField(default=0)),
                ('last_request', models.CharField(blank=True, max_length=60, null=True)),
                ('last_order', models.CharField(blank=True, max_length=60, null=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('port', models.CharField(blank=True, max_length=5, null=True)),
                ('heading', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(db_index=True, max_length=4)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('altitude', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(50, 'AWOS, ASOS or ATIS'), (51, 'Unicom'), (52, 'Clearance Delivery'), (53, 'Ground Control'), (54, 'Tower'), (55, 'Approach'), (56, 'Departure')])),
                ('frequency', models.IntegerField(help_text='Frequency in MhZ * 100 (eg. 12345 for 123.45 Mhz)')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(help_text='The name used in ATC communications', max_length=60)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms', to='fgserver.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetarObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cycle', models.IntegerField()),
                ('observation', models.CharField(max_length=255)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metar', to='fgserver.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('order', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('confirmed', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('acked', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='fgserver.Aircraft')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='fgserver.Comm')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('request', models.CharField(max_length=255)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='fgserver.Comm')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='fgserver.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('bearing', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('width', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='fgserver.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='StartupLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('altitude', models.IntegerField(default=0)),
                ('heading', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startup_location', to='fgserver.Aircraft')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='fgserver.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='WayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('altitude', models.FloatField(default=0)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Point'), (1, 'Airport'), (2, 'Nav'), (3, 'Fix'), (4, 'Taxi'), (5, 'Runway'), (6, 'Parking'), (7, 'Pushback'), (8, 'Circuit'), (9, 'Hold')], null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Stopped'), (2, 'Pushback'), (3, 'Taxiing'), (4, 'Departing'), (5, 'Turning'), (6, 'Climbing'), (7, 'Cruising'), (8, 'Approaching'), (9, 'Landing'), (10, 'Touchdown'), (11, 'Crosswind'), (12, 'Downwind'), (13, 'Base'), (14, 'Straight'), (15, 'Final'), (16, 'Short of runway'), (17, 'Lined up'), (18, 'Tunned'), (19, 'Parking'), (20, 'Lining up')], null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('flightplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fgserver.FlightPlan')),
                ('radius', models.FloatField(default=3704.0)),
                ('altitude', models.FloatField(default=304.8)),
                ('enabled', models.BooleanField(default=False)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='fgserver.Airport')),
            ],
            bases=('fgserver.flightplan',),
        ),
        migrations.CreateModel(
            name='CircuitWaypoint',
            fields=[
                ('waypoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fgserver.WayPoint')),
                ('circuit_type', models.IntegerField(blank=True, choices=[(0, 'Straight'), (1, 'Crosswind'), (2, 'Downwind'), (3, 'Base'), (4, 'Final')], null=True)),
            ],
            bases=('fgserver.waypoint',),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='flightplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='fgserver.FlightPlan'),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='fgserver.Aircraft'),
        ),
    ]
