# Generated by Django 2.1.7 on 2019-03-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgserver', '0003_order_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
