# Generated by Django 2.1.7 on 2019-05-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgserver', '0004_airport_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
