# Generated by Django 2.1.7 on 2020-04-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgserver', '0005_aircraft_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
