# Generated by Django 2.1.7 on 2020-04-28 18:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fgserver', '0007_request_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Position')),
                ('orientation', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Orientation')),
                ('linear_vel', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Linear velocity')),
                ('angular_vel', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Angular velocity')),
                ('linear_accel', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Linear acceleration')),
                ('angular_accel', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Angular acceleration')),
                ('request', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('on_ground', models.BooleanField(default=False)),
                ('freq', models.IntegerField(default=0)),
                ('message', models.CharField(default='Hello!', max_length=255)),
                ('state', models.IntegerField(default=0)),
                ('aircraft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='fgserver.Aircraft', verbose_name='Aircraft status')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='confirmed',
            new_name='expired',
        ),
        migrations.AddField(
            model_name='order',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
