# Generated by Django 2.1.7 on 2020-04-28 20:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fgserver', '0008_auto_20200428_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftstatus',
            name='angular_accel',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326, verbose_name='Angular acceleration'),
        ),
        migrations.AlterField(
            model_name='aircraftstatus',
            name='angular_vel',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326, verbose_name='Angular velocity'),
        ),
        migrations.AlterField(
            model_name='aircraftstatus',
            name='linear_accel',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326, verbose_name='Linear acceleration'),
        ),
        migrations.AlterField(
            model_name='aircraftstatus',
            name='linear_vel',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326, verbose_name='Linear velocity'),
        ),
        migrations.AlterField(
            model_name='aircraftstatus',
            name='orientation',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='aircraftstatus',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326, verbose_name='Position'),
        ),
    ]
