# Generated by Django 5.1.6 on 2025-02-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fgserver', '0010_auto_20200429_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startuplocation',
            options={'ordering': ['airport', 'name']},
        ),
    ]
