# Generated by Django 2.1.7 on 2019-03-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fgserver', '0002_auto_20190311_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('altitude', models.FloatField(default=0)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Point'), (1, 'Airport'), (2, 'Nav'), (3, 'Fix'), (4, 'Taxi'), (5, 'Runway'), (6, 'Parking'), (7, 'Pushback'), (8, 'Circuit'), (9, 'Hold')], null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Stopped'), (2, 'Pushback'), (3, 'Taxiing'), (4, 'Departing'), (5, 'Turning'), (6, 'Climbing'), (7, 'Cruising'), (8, 'Approaching'), (9, 'Landing'), (10, 'Touchdown'), (11, 'Crosswind'), (12, 'Downwind'), (13, 'Base'), (14, 'Straight'), (15, 'Final'), (16, 'Short of runway'), (17, 'Lined up'), (18, 'Tunned'), (19, 'Parking'), (20, 'Lining up')], null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('flightplan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ai.FlightPlan')),
                ('radius', models.FloatField(default=3704.0)),
                ('altitude', models.FloatField(default=304.8)),
                ('enabled', models.BooleanField(default=False)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='fgserver.Airport')),
            ],
            bases=('ai.flightplan',),
        ),
        migrations.CreateModel(
            name='CircuitWaypoint',
            fields=[
                ('waypoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ai.WayPoint')),
                ('circuit_type', models.IntegerField(blank=True, choices=[(0, 'Straight'), (1, 'Crosswind'), (2, 'Downwind'), (3, 'Base'), (4, 'Final')], null=True)),
            ],
            bases=('ai.waypoint',),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='flightplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='ai.FlightPlan'),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='fgserver.Aircraft'),
        ),
    ]
