# Generated by Django 2.1.7 on 2020-04-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuit',
            name='enabled',
        ),
        migrations.AddField(
            model_name='flightplan',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='handler',
            field=models.CharField(default='fgserver.ai.handlers.CircuitHandler', max_length=255),
            preserve_default=False,
        ),
    ]
