# Generated by Django 2.1.7 on 2020-05-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_auto_20200520_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinode',
            name='on_runway',
            field=models.BooleanField(default=False),
        ),
    ]
