# Generated by Django 2.1.7 on 2020-05-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_taxinode_on_runway'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiway',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Stopped'), (2, 'Pushback'), (3, 'Taxiing'), (4, 'Departing'), (5, 'Turning'), (6, 'Climbing'), (7, 'Cruising'), (8, 'Approaching'), (9, 'Landing'), (10, 'Touchdown'), (11, 'Crosswind'), (12, 'Downwind'), (13, 'Base'), (14, 'Straight'), (15, 'Final'), (16, 'Short of runway'), (17, 'Lined up'), (18, 'Tunned'), (19, 'Parking'), (20, 'Lining up'), (21, 'On Hold'), (22, 'Rolling'), (23, 'Cross rwy')], null=True),
        ),
    ]
