# Generated by Django 5.1.6 on 2025-02-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_auto_20200520_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightplan',
            name='handler',
            field=models.CharField(choices=[('Circuit', 'fgserver.ai.handler.CircuitHandler')], max_length=255),
        ),
        migrations.AlterField(
            model_name='taxinode',
            name='adjacents',
            field=models.ManyToManyField(to='ai.taxinode'),
        ),
    ]
