# Generated by Django 5.1.6 on 2025-03-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_alter_flightplan_handler_alter_taxinode_adjacents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightplan',
            name='handler',
            field=models.CharField(choices=[('Circuit', 'fgserver.ai.handlers.CircuitHandler'), ('fgserver.ai.handlers.CircuitHandler', 'Circuit pattern')], max_length=255),
        ),
    ]
