# Generated by Django 5.1.6 on 2025-03-30 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_alter_flightplan_handler'),
        ('fgserver', '0011_alter_startuplocation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxiway',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxiways', to='fgserver.airport'),
        ),
    ]
