# Generated by Django 5.1.6 on 2025-04-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_alter_taxiway_airport'),
        ('fgserver', '0011_alter_startuplocation_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Circuit',
        ),
        migrations.AddField(
            model_name='flightplan',
            name='altitude',
            field=models.FloatField(default=304.8),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='arrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='fgserver.airport'),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='fgserver.airport'),
        ),
    ]
