# Generated by Django 5.1.6 on 2025-04-13 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_flightplan_altitude_flightplan_arrival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='handler',
            field=models.CharField(choices=[('fgserver.ai.handlers.CircuitHandler', 'Circuit pattern'), ('fgserver.ai.handlers.TripHandler', 'Normal Trip')], max_length=255),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='fdm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flightplans', to='ai.fdm'),
        ),
        migrations.CreateModel(
            name='FDMState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('stopped', 'Stopped'), ('starting', 'Starting'), ('pushback', 'Pushback'), ('taxiing', 'Taxiing'), ('holding', 'Holding'), ('short', 'Short'), ('linedup', 'Linedup'), ('departing', 'Departing'), ('climbing', 'Climbing'), ('cruising', 'Cruising'), ('approaching', 'Approaching'), ('on_circuit', 'On_circuit'), ('rejoining', 'Rejoining'), ('landing', 'Landing'), ('rolling', 'Rolling'), ('crossing', 'Crossing')], max_length=16)),
                ('speed', models.IntegerField(help_text='in Knots')),
                ('vertical_speed', models.IntegerField(help_text='in Feets per minute')),
                ('turn_rate', models.IntegerField(help_text='Degrees/second')),
                ('target_vertical_speed', models.IntegerField(help_text='in Feets per minute')),
                ('fdm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='ai.fdm')),
            ],
        ),
        migrations.DeleteModel(
            name='CircuitWaypoint',
        ),
    ]
