# Generated by Django 5.1.6 on 2025-04-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_fdm_alter_flightplan_handler_flightplan_fdm_fdmstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdm',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
