# Generated by Django 5.1.6 on 2025-04-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_alter_fdm_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fdmstate',
            name='target_vertical_speed',
        ),
        migrations.AddField(
            model_name='fdmstate',
            name='acceleration',
            field=models.IntegerField(default=0, help_text='in m/s2'),
        ),
    ]
