# Generated by Django 5.1.6 on 2025-04-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_remove_fdmstate_target_vertical_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdmstate',
            name='acceleration',
            field=models.FloatField(default=0, help_text='in m/s2'),
        ),
    ]
