# Generated by Django 5.1.6 on 2025-04-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_alter_fdmstate_acceleration'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdm',
            name='landing_distance',
            field=models.IntegerField(default=0, help_text='in meters'),
        ),
        migrations.AddField(
            model_name='fdm',
            name='takeoff_distance',
            field=models.IntegerField(default=0, help_text='in meters'),
        ),
    ]
